# Generated by Django 5.2.17 on 2026-10-02 09:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='attendance_qr_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
