# Generated by Django 5.2.17 on 2026-10-06 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollperiod',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft (Consolidating)'), ('PENDING_APPROVAL', 'Pending Client Approval'), ('APPROVED', 'Approved (Ready to Pay)'), ('PAID', 'Paid (Payslips Distributed)')], default='DRAFT', max_length=20),
        ),
    ]
