# Generated by Django 5.2.17 on 2026-10-06 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_attendance_qr_token'),
        ('onboarding', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeOnboardingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='companies.company')),
                ('onboarding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_tasks', to='onboarding.employeeonboarding')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onboarding.onboardingtask')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
